############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1998  Microsoft Corporation.  All Rights Reserved.
#
#   File:   makefile
#   Content:    redirect make process to real build instructions
#
############################################################################

!ifdef NTMAKEENV
#   NT environment build
!include $(NTMAKEENV)\makefile.def

!else

!error Build environment not defined!

!endif
